[RSN-9] - Implemented DTO models on frontend
wzarek/Reasn pull request #15
Opened 2024-04-22 16:22 UTC by wzarek

## Description
Implemented models from DTO on backend to frontend with mappers from JSON string and object with unit tests.

## Related issue and/or ticket
RSN-9

2024-05-03 22:51 UTC, raczu commented on Client/reasn-client/packages/common/models/EventDto.ts
> +        if ('Tags' in obj === false || obj.Tags === null || !Array.isArray(obj.Tags)) throw new ModelMappingError('EventDto','Tags is required')
The way to validate responses from API and creating the appropriate DTOs from them seems very complicated especially for DTOs with a large number of properties such as this one. What's more, the DTO by the definition should not have any methods so parsers or validators should be implemented as independent functions. I would consider making universal validator to somehow simplify this logic or use third party (lightweight) library to do so.

2024-05-03 23:08 UTC, raczu requested changes
After a long research and consideration of all possibilites, I think that the best solution will be to use [zod](https://zod.dev/) - it does not depend on other libraries and is lightweight. This will greatly simplify the verification of data received from the API. Additionally, we will be able to use this library also to verify the data provided by the user (data from forms).

See below example, which shows an easy way to handle date conversion to proper object:
<img width="1679" alt="Screenshot 2024-05-04 at 1 06 12 AM" src="https://github.com/wzarek/Reasn/assets/61229912/07a04b12-c206-4cde-972a-de539f54a249">

2024-05-11 19:19 UTC, raczu requested changes
Apply those changes where its needed.

2024-05-12 18:55 UTC, wzarek commented on Client/reasn-client/packages/common/models/AddressDto.ts
> +            throw new ModelMappingError('AddressDto', result.error.message)
Yes, correct - it is not a proper way of handling errors when using **parse**. But we don't use **parse** here :) I will expand our Mapping error to have also this validation error list, so it should be fine then.

2024-05-12 18:58 UTC, wzarek commented on Client/reasn-client/packages/common/models/CommentDto.ts
> +    CreatedAt: z.string().or(z.date()).transform(arg => new Date(arg)),
I have changed it a bit, I missed your comment there, so used zod string formats to check if it's a UTC formatted string or a Date type.

2024-05-19 11:26 UTC, raczu approved these changes

2024-06-09 18:15 UTC, wzarek commented
@raczu if everything is done please merge, checked partially and looks fine

2024-06-09 20:27 UTC, merged