[RSN-45] - Change parameters architecture, replaced role, status, object type with enum
wzarek/Reasn pull request #31
Opened 2024-05-09 12:15 UTC by mkoper02

## Description
Changed _Status_, _Role_, _Object_Type_ into enum in db, created new enum _Type_ and added it to parameters table

## Related issue and/or ticket

2024-05-09 16:14 UTC, wzarek requested changes

2024-05-09 16:14 UTC, wzarek commented on Database/init-constraints.sql
>  	END IF;
Should't it be that if 'Event' then get from events.event, if 'User' then from users.user

2024-05-09 16:14 UTC, wzarek commented on Database/init-constraints.sql
> +-- );
This one we can do directly on events.event and users.user, add check where it's status will be in X. Just like it was but not for status table but for each status column directly check the values of enum.

2024-05-09 16:14 UTC, wzarek commented on Database/init-db.sql
> +  "type" common.type NOT NULL,
Didn't we agree on making those only in frontend (for proper validation) and leave the database as it was?

2024-05-10 15:27 UTC, wzarek approved these changes
OK

2024-05-10 15:28 UTC, wzarek commented
@mkoper02 remember to rebase and review conflicts

2024-05-10 17:16 UTC, wzarek requested changes

2024-05-10 17:16 UTC, wzarek commented on Database/init-db.sql
> +  "value" text NOT NULL CONSTRAINT events_patameter_value_maxlength CHECK (LENGTH("value") <= 64)
Add comma here :)

2024-05-10 17:19 UTC, wzarek approved these changes

2024-05-11 19:42 UTC, raczu approved these changes
lgtm

2024-05-11 19:48 UTC, merged