[RSN-65] - Implemented base routing and base register page
wzarek/Reasn pull request #51
Opened 2024-06-08 00:41 UTC by wzarek

## Description
Really base routing + register page + login page placeholder

## Related issue and/or ticket
RSN-65

2024-06-08 20:02 UTC, raczu requested changes

2024-06-08 20:02 UTC, raczu commented on Client/reasn-client/apps/web/app/register/user/page.tsx
> +              <FloatingInput type="password" label="hasło" />
Add field for confirming password - it will prevent the user from making mistake when entering the password

2024-06-08 20:02 UTC, raczu commented on Client/reasn-client/apps/web/app/register/user/page.tsx
> +            to jak, zorganizujesz <br /> nam coś?
Change this to more user-related text

2024-06-09 17:56 UTC, wzarek commented
@raczu please check and keep in mind that this is not the final verison of how those forms will look like, there will be functionality to choose their interest implemented and the fields may be slightly changes (especially for some dropdowns in country, real-time validations etc.)

2024-06-09 19:57 UTC, raczu approved these changes

2024-06-09 20:40 UTC, merged